### ISSUE TITLE
ChatOptionList State save

### ISSUE THREAD

**Issue by maheshfiscal** [watson-developer-cloud/assistant-demo#19]
When I select an option-item from a option-list in a chat window, List disappears.
How can I persist the state of option-list? i.e. After select Bot option-list should not disappear.

const options = this.props.isLastMessage || this.state.options[0].isSelected ? this.state.options : []; 

On User click, we do:
 this.setState({ options: [Object.assign(option, { isSelected: true })] });
which overrides the original data binding of the control.

**Comment by Oliver-I** [comment]
@maheshfiscal There may also be React components involved. @repjarms Do you have any guidance here?

**Comment by repjarms** [comment]
@maheshfiscal yes you are on the right track on how to change the behavior to persist the chat options after a user selects an option.

There are two key areas in `ChatOptionsList` that enable this behavior.

1. `onOptionSelect()` removes all options other than the one selected
2. The `render()` method only renders the list if it is the latest message in the chatlist, or if the first option in the list is selected. Since we remove all elements besides the selected one, this is basically like saying "before the user selects a chat option, show the full list, after the user selects an option, make sure they selected an option and then show the list".

So, in order to change this to get the behavior you want, you'll need to make a couple changes:

https://github.com/watson-developer-cloud/assistant-demo/blob/master/src/components/ChatOptionList/ChatOptionList.js#L21

On this line, we have 

```
this.setState({ options: [Object.assign(option, { isSelected: true })] });
```

This would need to be changed to keep all of the chat options, while updating the selected option inline.

```
  optionSelect(selectedOption) {
    const updatedOptions = this.state.options.map((option) => {
      if (option.value.input.text === selectedOption.value.input.text) {
        return { ...option, isSelected: true };
      } else {
        return option;
      }
    });
    this.setState({ options: updatedOptions });
    this.props.onUserInput('option', selectedOption.value.input.text);
  }
```

Secondly, you'd want to change the check in the render method to always show the chat options.

https://github.com/watson-developer-cloud/assistant-demo/blob/master/src/components/ChatOptionList/ChatOptionList.js#L26

So instead of the check on that line, you'd use this:

```
const { options } = this.state;
```

This just takes the options array from state and uses that.

Please note that there are other things that you will have to change, like some of the CSS in `ChatOption.scss`, to remove some of the animation effects when a chat option is selected.

*Disclaimer:* I have not tested this out completely using the app, but I believe these changes should get your moving in the right direction. I'm happy to test out further if there are issues after making those changes.

And finally, here is the full file with the changes for context:

```
import React from 'react';
import PropTypes from 'prop-types';
import ChatOption from '../ChatOption/ChatOption';
import CreditCardOption from '../CreditCardOption/CreditCardOption';
import ChatUnorderedList from '../ChatUnorderedList/ChatUnorderedList';

class ChatOptionList extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      options: [],
    };
  }

  componentWillMount() {
    this.setState({ options: this.props.options });
  }

  optionSelect(selectedOption) {
    const updatedOptions = this.state.options.map((option) => {
      if (option.value.input.text === selectedOption.value.input.text) {
        return { ...option, isSelected: true };
      } else {
        return option;
      }
    });
    this.setState({ options: updatedOptions });
    this.props.onUserInput('option', selectedOption.value.input.text);
  }

  render() {
    const { options } = this.state;

    if (this.props.type === 'creditCard') {
      return (
        <div>
          {options.map(option => (
            <CreditCardOption
              cardName={option.cardName}
              description={option.description}
              onUserInput={(value) => {
                this.onUserInput(value);
              }}
            />
          ))}
        </div>
      );
    }
    if (this.props.type === 'button') {
      return (
        <div className="chat-option-list">
          {options.map(option => (
            <ChatOption
              key={option.value.input.text}
              option={option}
              onUserInput={(selectedOption) => {
                this.optionSelect(selectedOption);
              }}
              isSelected={option.isSelected}
            />
          ))}
        </div>
      );
    }
    if (this.props.type === 'list') {
      return (
        <div className="chat-option-list">
          <ChatUnorderedList
            options={options}
            onUserInput={(selectedOption) => {
              this.optionSelect(selectedOption);
            }}
            isSelected={this.state.options[0].isSelected}
          />
        </div>
      );
    }
    return null;
  }
}

ChatOptionList.propTypes = {
  type: PropTypes.string.isRequired,
  options: PropTypes.array.isRequired,
  onUserInput: PropTypes.func.isRequired,
  isLastMessage: PropTypes.bool.isRequired,
};

export default ChatOptionList;
```

**Comment by Oliver-I** [comment]
@repjarms Thank you.
@maheshfiscal I will now close this ticket. Please note for future queries about modifying the code you should use developer sources such as https://developer.ibm.com/answers/index.html, this repository should be used for issues with the code being provided.
